task: detection

num_classes: 1
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/kaggle/working/cocodataset/train/image/
    ann_file: /home/kaggle/working/cocodataset/train/labels.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 24
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/kaggle/working/cocodataset/valid/image
    ann_file: /home/kaggle/working/cocodataset/valid/labels.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 24
  num_workers: 4
  drop_last: False